# Generated by Django 4.0 on 2022-09-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
