# Generated by Django 4.0 on 2022-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_description_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='body',
            field=models.TextField(),
        ),
    ]
